---
title: "CodeBook/Data Dictionary"
author: "JLR"
date: "1/8/2021"
output: rmarkdown::github_document
  

---
### PURPOSE

This document describes the data layout of the "tidy" data set generated by the 
_run_analysis()_ R program.  The data to be analyzed will be downloaded from the [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).  The data used to generated the output dataset is stored in a .zip file which includes the following key files:

- 'train/X_train.txt': Training set of sensor observations

- 'train/y_train.txt': Training activity indices which are mapped to 'activity_labels.txt'.

- 'test/X_test.txt': Test set of sensor observations

- 'test/y_test.txt': Test activity indices which are mapped to 'activity_labels.txt'.

- 'test/subject_test.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

- 'train/subject_train.txt': Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30. 

The /train and /test folders provide the data to be analyzed.  Each row in the files provides:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Numeric index to the daily activities (indexed in the 'activity_labels.txt' dataset). 
- A numeric identifier of the subject who carried out the experiment.

The diagram below provides a high-level flow of the key input files.

![DataFlow](https://user-images.githubusercontent.com/75954319/104103205-e5c97f00-526e-11eb-9d6d-575e6478d078.png)
  



### DATA DEFINITIONS FOR TIDY DATA ANALYSIS DATASET (OUTPUT)

The output dataset is a summary of the detailed observations.  The observations are summarized by Test Subject (the person who was wearing sensing device) and Activity.  A mean calculation is prepared for each variable at the summary level.

```{r}
cb <- read.csv("CodeBook.csv", header=TRUE)
knitr::kable(cb
             )
```